questions = [
    "Qu'est-ce que le support informatique selon l'ouvrage ?",
    "Quels sont les objectifs principaux d'un technicien de support ?",
    "Pourquoi la communication humaine est-elle cruciale en IT ?",
    "Quelle est la différence entre le support réactif et proactif ?",
    "Comment définir une approche efficace pour aider les utilisateurs ?",
    "Quel rôle joue l'empathie dans le dépannage ?",
    "Comment le livre décrit-il l'évolution du support informatique ?",
    "Quels sont les composants de base d'un système de support ?",
    "Pourquoi ne faut-il jamais faire d'hypothèses sur les connaissances de l'utilisateur ?",
    "Comment gérer les attentes des utilisateurs ?",
    "Quels sont les premiers pas lors de la réception d'un appel de support ?",
    "Quelle est l'importance de la documentation initiale ?",
    "Comment traiter chaque utilisateur comme un individu unique ?",
    "Quels sont les défis courants mentionnés dans l'introduction ?",
    "Quel est l'impact d'un mauvais support sur une entreprise ?",
    "Comment évaluer le niveau de compétence technique d'un utilisateur ?",
    "Quels sont les différents styles d'apprentissage mentionnés ?",
    "Pourquoi utiliser des groupes de pairs mixtes lors de formations ?",
    "Comment structurer une session d'éducation pour les employés ?",
    "Quelle est l'importance de mettre les concepts informatiques en contexte ?",
    "Comment définir des objectifs pédagogiques clairs ?",
    "Qu'est-ce que la méthode 'Écouter et Répéter' dans la formation ?",
    "Comment consolider les connaissances après une formation ?",
    "Pourquoi la langue utilisée par le technicien est-elle importante ?",
    "Comment expliquer des termes comme UEFI ou USB-C à un novice ?",
    "Quel est le rôle du 'Staff Training' dans la réduction des tickets ?",
    "Comment gérer les utilisateurs qui 'savent tout' ?",
    "Comment motiver un utilisateur à apprendre ?",
    "Quelle est l'efficacité de l'utilisation de vidéos vs manuels écrits ?",
    "Comment évaluer le succès d'une formation ?",
    "Quelle est la première question à poser lors d'une panne matérielle ?",
    "Comment identifier si un problème est local ou global ?",
    "Qu'est-ce que la recherche de la 'Root Cause' (cause racine) ?",
    "Pourquoi le redémarrage est-il une étape logique de début ?",
    "Comment utiliser le gestionnaire de tâches pour diagnostiquer un souci ?",
    "Quelle est la différence entre le Gestionnaire de tâches et le Moniteur de ressources ?",
    "Comment l'historique des changements récents aide-t-il au diagnostic ?",
    "Quelles sont les étapes d'un flowchart de dépannage efficace ?",
    "Pourquoi ne faut-il jamais exclure une cause jugée 'impossible' ?",
    "Comment isoler un problème logiciel d'un problème matériel ?",
    "Quelle est l'importance de la logique de flux dans le diagnostic ?",
    "Comment gérer les pannes intermittentes ?",
    "Comment utiliser les journaux d'événements (Event Logs) ?",
    "Comment diagnostiquer un problème de connexion réseau complexe ?",
    "Quel est l'impact des facteurs environnementaux sur le matériel ?",
    "Comment reformuler une question technique pour un utilisateur ?",
    "Comment vérifier les câbles sans offenser l'utilisateur ?",
    "Pourquoi éviter de sur-taxer ses propres capacités de réflexion ?",
    "En quoi consiste l'approche 'Step-by-step' ?",
    "Comment documenter la solution trouvée de manière exploitable ?",
    "Comment dépanner les pilotes de périphériques (drivers) ?",
    "Quand faut-il effectuer un 'Roll back' de pilote ?",
    "Quel est le rôle d'un UPS dans la protection du matériel ?",
    "Quels sont les types de périphériques de saisie spécialisés mentionnés ?",
    "Comment tester l'intégrité d'une clé USB ?",
    "Quelles sont les problématiques courantes liées aux écrans et moniteurs ?",
    "Comment gérer les problèmes de stockage externe ?",
    "Quels sont les défis spécifiques des imprimantes en réseau ?",
    "Quel est l'impact de la foudre et des surtensions sur les PC ?",
    "Comment identifier un composant matériel défaillant au démarrage ?",
    "Comment gérer les conflits de périphériques Bluetooth ?",
    "Quelle est la différence entre l'USB-C et les anciens standards ?",
    "Qu'est-ce que la maintenance préventive du matériel ?",
    "Comment nettoyer en toute sécurité des composants internes ?",
    "Comment utiliser l'outil de diagnostic système de Windows ?",
    "Qu'est-ce que la 'vigilance de sécurité' pour un technicien support ?",
    "Comment expliquer l'authentification multifacteur à un utilisateur ?",
    "Quels sont les risques liés aux clés USB inconnues ?",
    "Comment identifier une tentative de phishing signalée par un utilisateur ?",
    "Pourquoi les mises à jour de sécurité régulières sont-elles vitales ?",
    "Quelle est la procédure pour la gestion des mots de passe oubliés ?",
    "Que faire en cas de suspicion d'infection par un malware ?",
    "Quel est le rôle des pare-feux dans la connectivité réseau ?",
    "Comment sensibiliser le personnel au Social Engineering ?",
    "Quels sont les enjeux de sécurité des appareils mobiles ?",
    "Qu'est-ce que l'alliance 'Five Eyes' mentionnée dans le livre ?",
    "Quelle est l'importance du chiffrement AES 256-bit ?",
    "Comment sécuriser un accès à distance via TeamViewer ?",
    "Comment gérer les privilèges administrateur pour les utilisateurs ?",
    "Quelle est la procédure de sauvegarde en cas d'attaque par ransomware ?",
    "Pourquoi la paperasse (SLA, rapports) est-elle importante ?",
    "Comment éviter de noyer les rapports dans des détails non pertinents ?",
    "Quel est le rôle du support de deuxième et troisième ligne ?",
    "Comment transférer efficacement un ticket au niveau supérieur ?",
    "Quelle est l'importance du feedback après la résolution d'un problème ?",
    "Comment gérer un utilisateur en colère ou frustré ?",
    "Quelles sont les bonnes pratiques d'utilisation de TeamViewer ?",
    "Comment le suivi des actifs (Asset Tags) réduit la charge de travail ?",
    "Pourquoi la curiosité est-elle une qualité pour un technicien IT ?",
    "Comment structurer les équipes de support pour plus d'efficacité ?",
    "Comment gérer le stress en période de crise informatique ?",
    "Comment équilibrer rapidité de résolution et qualité de service ?",
    "Comment rédiger un guide 'How-to' efficace pour les utilisateurs ?",
    "Pourquoi la ponctualité est-elle cruciale pour les techniciens de terrain ?",
    "Comment gérer les interruptions constantes pendant le travail ?",
    "À quoi servent les sections d'informations supplémentaires ?",
    "Comment le support informatique contribue à la productivité globale ?",
    "Quelles sont les règles d'éthique concernant les données ?",
    "Comment rester à jour face aux évolutions technologiques ?",
    "Quel est l'impact de la culture d'entreprise sur le support IT ?"
]